spring:
  application:
    name: productos-service
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

mensaje: "productos-service usando configuración remota"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
